"""Constants and output schemas shared by SEC extraction modules."""

from __future__ import annotations

from pathlib import Path

BASE_DATA_URL = "https://data.sec.gov"
BASE_ARCHIVES_URL = "https://www.sec.gov/Archives/edgar/data"
SEC_CIK_LOOKUP_URL = "https://www.sec.gov/Archives/edgar/cik-lookup-data.txt"
DEFAULT_OUTPUT_DIR = Path("output") / "sec_company_extraction"
DEFAULT_USER_AGENT = "KCNSC (aarango@kcnsc.doe.com)"
REQUEST_DELAY_SECONDS = 0.2
TIMEOUT_SECONDS = 30
APPROVED_REVIEW_STATUS = "approved"
DEFAULT_FINANCIAL_YEARS = 10
HIGH_VALUE_10K_ITEMS = {
    "Item 1",
    "Item 1A",
    "Item 1C",
    "Item 3",
    "Item 7",
    "Item 7A",
    "Item 8",
    "Item 9A",
}

EXTRACT_FIELDNAMES = [
    "record_type",
    "original_company_name",
    "ultimate_parent_name",
    "ultimate_parent_uei",
    "ticker",
    "cik",
    "company_name",
    "source_form",
    "source_url",
    "field_name",
    "field_value",
    "taxonomy",
    "tag",
    "label",
    "description",
    "unit",
    "value",
    "period_start",
    "period_end",
    "fiscal_year",
    "fiscal_period",
    "xbrl_frame",
    "accession_number",
    "text_preview",
]
PROFILE_FIELDNAMES = [
    "original_company_name",
    "ultimate_parent_name",
    "ultimate_parent_uei",
    "sec_company_name",
    "ticker",
    "cik",
    "entity_type",
    "sic",
    "sic_description",
    "fiscal_year_end",
    "state_of_incorporation",
    "state_of_incorporation_description",
    "business_city",
    "business_state_or_country",
    "business_zip_code",
    "mailing_city",
    "mailing_state_or_country",
    "phone",
    "website",
    "investor_website",
    "match_method",
    "match_confidence",
    "review_status",
    "review_notes",
]
SEC_10K_SECTION_FIELDNAMES = [
    "original_company_name",
    "ultimate_parent_name",
    "ultimate_parent_uei",
    "sec_company_name",
    "ticker",
    "cik",
    "source_form",
    "accession_number",
    "item",
    "heading",
    "text_length",
    "text_preview",
    "source_url",
]
ANNUAL_FINANCIAL_FIELDNAMES = [
    "original_company_name",
    "ultimate_parent_name",
    "ultimate_parent_uei",
    "sec_company_name",
    "ticker",
    "cik",
    "fiscal_year",
    "revenues",
    "revenue_from_contract",
    "sales_revenue_net",
    "reported_revenue",
    "net_income_loss",
    "assets",
    "liabilities",
    "stockholders_equity",
    "cash_and_cash_equivalents",
    "operating_cash_flow",
    "capital_expenditures",
    "total_debt",
    "current_assets",
    "current_liabilities",
    "gross_profit",
    "operating_income_loss",
    "reported_source_tags",
    "data_quality_notes",
]
AWARD_SEC_SUMMARY_FIELDNAMES = [
    "original_company_name",
    "ultimate_parent_name",
    "ultimate_parent_uei",
    "sec_company_name",
    "ticker",
    "cik",
    "fiscal_year",
    "total_award_amount",
    "award_count",
    "recipient_count",
    "awarding_agency_count",
    "reported_revenue",
    "net_income_loss",
    "assets",
    "liabilities",
    "award_to_revenue_ratio",
    "data_coverage_flag",
]
CROSSWALK_FIELDNAMES = [
    "original_company_name",
    "ultimate_parent_name",
    "ultimate_parent_uei",
    "sec_match_name",
    "sec_match_scope",
    "sec_company_name",
    "ticker",
    "cik",
    "sec_record_found",
    "sec_record_status",
    "sec_match_source",
    "match_method",
    "match_confidence",
    "review_status",
    "review_notes",
]
BATCH_SUMMARY_FIELDNAMES = [
    "original_company_name",
    "ultimate_parent_name",
    "ultimate_parent_uei",
    "ticker",
    "cik",
    "sec_company_name",
    "status",
    "output_dir",
    "xbrl_fact_count",
    "ten_k_section_count",
    "error",
]
SEC_FINANCIAL_TAG_MAP = {
    "Revenues": "revenues",
    "RevenueFromContractWithCustomerExcludingAssessedTax": "revenue_from_contract",
    "SalesRevenueNet": "sales_revenue_net",
    "NetIncomeLoss": "net_income_loss",
    "Assets": "assets",
    "Liabilities": "liabilities",
    "StockholdersEquity": "stockholders_equity",
    "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest": "stockholders_equity",
    "CashAndCashEquivalentsAtCarryingValue": "cash_and_cash_equivalents",
    "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents": "cash_and_cash_equivalents",
    "NetCashProvidedByUsedInOperatingActivities": "operating_cash_flow",
    "PaymentsToAcquirePropertyPlantAndEquipment": "capital_expenditures",
    "LongTermDebtAndFinanceLeaseObligationsCurrent": "total_debt",
    "LongTermDebtAndFinanceLeaseObligationsNoncurrent": "total_debt",
    "LongTermDebtCurrent": "total_debt",
    "LongTermDebtNoncurrent": "total_debt",
    "CurrentAssets": "current_assets",
    "AssetsCurrent": "current_assets",
    "CurrentLiabilities": "current_liabilities",
    "LiabilitiesCurrent": "current_liabilities",
    "GrossProfit": "gross_profit",
    "OperatingIncomeLoss": "operating_income_loss",
}
